# Generated by Django 5.1.5 on 2025-01-19 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('supplier', 'Supplier'), ('consumer', 'Consumer')], default='consumer', max_length=15),
            preserve_default=False,
        ),
    ]
